<?php

/*****CONSEJOS: DIAGRAMAS
 *Carpeta del proyecto btn Derecho/ diagramas.
 */

class Deportista extends Persona
{
    use Trabajador;

    public $queja;

    public function __construct(string         $nombre,
                                int            $edad,
                                int            $sueldo,
                                private int    $marca_personal,
                                private string $especialidad)
    {
        parent::__construct($nombre, $edad);
        echo "<h3>Nombre $this->nombre</h3>";
        $this->sueldo = $sueldo;
    }

    public
    function __toString(): string
    {
        return parent::__toString(). "sueldo $this->sueldo"."especialidad $this->especialidad"."mi marca personal: $this->marca_personal" ; // TODO: Change the autogenerated stub
    }


    public function queja()
    {
        return "Voy a bajar mi marca $this->marca_personal";
        // TODO: Implement queja() method.
    }
}